"""
Builds every artifact that describes a mineable resource block from the single
source of truth in resource_blocks.json:

  datapack/data/minecraft/loot_table/blocks/<block>.json
      The seed each stage drops, stamped with the resource block index and the
      stage that dropped it. Nothing else reports a broken block to a datapack.
  datapack/data/derailed/tags/block/<category>/mineable_<family>.json
      One tag per tool rule, so a rule can carry the speed that family needs.
  datapack/data/derailed/tags/block/<category>/unmineable.json
      Stage 0 blocks, which no tool may mine until reachability unlocks them.
      Rolled up with the mineable tags into <category>/all.json.
  datapack/data/derailed/function/generated/mined/*.mcfunction
      Two-layer dispatch: block index picks the file, stage picks the line.
  resourcepack/assets/minecraft/blockstates/<block>.json
      Each stage's model, one random variant per entry in model_names. The
      models themselves are hand-made and live under
      resourcepack/assets/derailed/models/block/<category>/.

Only the models and the block tags are free to sit in a category folder. A
block's loot table id is `id.withPrefix("blocks/")` and its blockstate is found
by `FileToIdConverter.json("blockstates")`, both keyed on the block's own
registry id, so those two are pinned flat and a subfolder would silently mean
"a file nothing loads".

Tool speeds are solved rather than declared. Mining time is
`ceil(hardness * 30 / speed)`, so a resource type states the stage_ticks it
wants and each family's speed follows from its hardness. That keeps every stage
of a chain feeling the same even though leaves and glass differ in hardness.
Print the solved rules with --rules and paste them into fix_items.mcfunction.

Generated paths are recorded in generated_manifest.json. A path that a previous
run wrote and this one did not is deleted, so renaming a block cannot leave a
stale loot table overriding vanilla behind.

Usage:
  py -3 generate_resource_blocks.py            write the generated files
  py -3 generate_resource_blocks.py --check    report drift without writing
  py -3 generate_resource_blocks.py --rules    also print the tool rule snippet
"""
import argparse
import json
import math
import re
import sys
from collections import defaultdict
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent  # repo root (one level up from utils/)
SOURCE_FILE = SCRIPT_DIR / "resource_blocks.json"
MANIFEST_FILE = SCRIPT_DIR / "generated_manifest.json"
LOAD_MCFUNCTION = ROOT / "datapack" / "data" / "derailed" / "function" / "load.mcfunction"

DATAPACK = ROOT / "datapack" / "data"
RESOURCEPACK = ROOT / "resourcepack" / "assets"

LOOT_TABLE_DIR = DATAPACK / "minecraft" / "loot_table" / "blocks"
TAG_DIR = DATAPACK / "derailed" / "tags" / "block"
FUNCTION_DIR = DATAPACK / "derailed" / "function" / "generated" / "mined"
BLOCKSTATE_DIR = RESOURCEPACK / "minecraft" / "blockstates"
MODEL_DIR = RESOURCEPACK / "derailed" / "models" / "block"

# The item a mined stage drops purely as a signal. It is read and killed by
#  'derailed:item/event/block_mined', never by a player
SEED_ITEM = "minecraft:wheat_seeds"

# Vanilla's mining time formula, ceil(hardness * 30 / speed)
TICKS_PER_HARDNESS = 30

# The most decimals a solved tool speed may use before the solver gives up
MAX_SPEED_DECIMALS = 6

BLOCK_SPEC = re.compile(r"^([a-z_]+)(?:\[([a-z_=,]+)\])?$")
CONST_SETTER = re.compile(r"^scoreboard players set (\$\w+) dr_const (\d+)\s*$")

GENERATED_HEADER = "# Generated by utils/generate_resource_blocks.py -- do not edit"


class SourceError(Exception):
    """A problem in resource_blocks.json that makes generation meaningless"""


def parse_block(spec):
    """Splits 'azalea_leaves[persistent=true]' into its id and its state map"""
    match = BLOCK_SPEC.match(spec)
    if not match:
        raise SourceError("block spec %r is not <id> or <id>[<k>=<v>,...]" % spec)
    block_id, state_text = match.groups()
    states = {}
    if state_text:
        for pair in state_text.split(","):
            key, _, value = pair.partition("=")
            if not value:
                raise SourceError("block spec %r has a state with no value" % spec)
            states[key] = value
    return block_id, states


def state_key(states):
    """The blockstate variant key for a state map, '' when there is none"""
    return ",".join("%s=%s" % (k, states[k]) for k in sorted(states))


def load_resource_ids():
    """Reads the resource type ids out of load.mcfunction so the numbers stay
    declared in exactly one place"""
    ids = {}
    for line in LOAD_MCFUNCTION.read_text(encoding="utf-8").splitlines():
        match = CONST_SETTER.match(line)
        if match:
            ids[match.group(1)] = int(match.group(2))
    return ids


def load_source():
    source = json.loads(SOURCE_FILE.read_text(encoding="utf-8"))
    families = {k: v for k, v in source["hardness_families"].items() if not k.startswith("_")}
    types = {k: v for k, v in source["resource_types"].items() if not k.startswith("_")}
    return families, types, source["resource_blocks"]


def family_of(families, block_id):
    """The hardness family a block belongs to, or None"""
    for name, family in families.items():
        if block_id in family["blocks"]:
            return name
    return None


def describe(index, entry):
    """How an entry is named in warnings, since entries carry no name field"""
    return "resource_blocks[%d] (biome %s, %s)" % (index, entry["biome"], entry["resource_type"])


def stage_models(types, entry, stage):
    """Every model a stage draws, relative to derailed:block/

    The resource type's category names the folder, the same one its block tags
    use, so a model and the tags describing it cannot end up apart. A stage that
    wants more than one random variant per name lists model_suffixes, which keeps
    model_names meaning one entry per species rather than one per variant"""
    category = types[entry["resource_type"]]["category"]
    return ["%s/%s%d%s" % (category, name, stage["model_id"], suffix)
            for name in entry["model_names"]
            for suffix in stage.get("model_suffixes", [""])]


def validate(families, types, blocks, resource_ids, warn):
    """Raises on anything that would generate a broken pack, and warns on
    anything that is merely unfinished"""
    # A block id carries one loot table and one blockstate, so every entry that
    #  lands on it has to agree about what it is
    role = {}
    owner = {}
    for index, entry in enumerate(blocks):
        label = describe(index, entry)
        resource = entry["resource_type"]
        if resource not in types:
            raise SourceError("%s uses undeclared resource_type %r" % (label, resource))
        if types[resource]["id"] not in resource_ids:
            raise SourceError("%s: %s is not set in load.mcfunction" % (label, types[resource]["id"]))
        if len(entry["stages"]) < 2:
            raise SourceError("%s needs a locked stage and at least one mineable stage" % label)

        for stage_index, stage in enumerate(entry["stages"]):
            block_id, _ = parse_block(stage["block"])
            mineable = stage.get("mineable", True)

            family = family_of(families, block_id)
            if family is None:
                raise SourceError("%s stage %d: %s is in no hardness family"
                                  % (label, stage_index, block_id))

            if role.setdefault(block_id, mineable) != mineable:
                raise SourceError(
                    "%s stage %d: %s is mineable in one chain and locked in another. Tags are "
                    "block-level, so a tool cannot tell them apart" % (label, stage_index, block_id))
            if owner.setdefault(block_id, resource) != resource:
                raise SourceError(
                    "%s stage %d: %s is already claimed by resource type %r"
                    % (label, stage_index, block_id, owner[block_id]))

        if not entry["model_names"]:
            warn("%s has no model_names, so its blockstates are not generated" % label)

    # Two resource types sharing a category would write their tags and models
    #  over each other
    claimed = {}
    for resource, spec in sorted(types.items()):
        if claimed.setdefault(spec["category"], resource) != resource:
            raise SourceError("resource types %r and %r both use category %r"
                              % (claimed[spec["category"]], resource, spec["category"]))

    # A model named by an entry but never drawn is a silent missing texture in
    #  game, so say so here instead
    for index, entry in enumerate(blocks):
        for stage in entry["stages"]:
            for path in stage_models(types, entry, stage):
                if not (MODEL_DIR / (path + ".json")).is_file():
                    warn("%s references missing model derailed:block/%s"
                         % (describe(index, entry), path))


def solved_speed(hardness, ticks):
    """The shortest tool speed that mines a block of this hardness in `ticks`

    Because the formula ceils, a whole range of speeds share a tick count -
    every s with hardness * 30 / ticks <= s < hardness * 30 / (ticks - 1). So
    rather than writing the exact quotient out to a fixed width, this walks
    decimal places from none upward and takes the first value that lands inside
    the window, which keeps the number in the tool rule readable. Rounding is
    always up, since rounding down leaves the division a hair past the tick it
    was solved for and the ceil turns that hair into a whole extra tick"""
    exact = hardness * TICKS_PER_HARDNESS / ticks
    for decimals in range(MAX_SPEED_DECIMALS + 1):
        scale = 10 ** decimals
        speed = math.ceil(exact * scale) / scale
        if speed > 0 and math.ceil(hardness * TICKS_PER_HARDNESS / speed) == ticks:
            return int(speed) if decimals == 0 else round(speed, decimals)
    raise SourceError(
        "no speed within %d decimals mines hardness %s in %d ticks - the window "
        "narrows as the tick count grows" % (MAX_SPEED_DECIMALS, hardness, ticks))


def build_loot_tables(blocks, out):
    """One loot table per block id, with an entry for every mineable stage that
    lands on it"""
    entries_by_block = defaultdict(list)
    for index, entry in enumerate(blocks):
        for stage_index, stage in enumerate(entry["stages"]):
            if not stage.get("mineable", True):
                continue
            block_id, states = parse_block(stage["block"])
            entries_by_block[block_id].append((states, index, stage_index))

    for block_id, stages in sorted(entries_by_block.items()):
        pool_entries = []
        for states, index, stage_index in stages:
            pool_entry = {
                "type": "minecraft:item",
                "name": SEED_ITEM,
            }
            if states:
                pool_entry["conditions"] = [{
                    "condition": "minecraft:block_state_property",
                    "block": "minecraft:" + block_id,
                    "properties": states,
                }]
            pool_entry["functions"] = [{
                "function": "minecraft:set_custom_data",
                "tag": "{dr_mined:{block:%d,stage:%d}}" % (index, stage_index),
            }]
            pool_entries.append(pool_entry)

        out[LOOT_TABLE_DIR / (block_id + ".json")] = {
            "type": "minecraft:block",
            "pools": [{"rolls": 1, "entries": pool_entries}],
        }


def build_blockstates(types, blocks, out):
    """Merges every entry that draws on a block id into one variants map, one
    random model variant per name in model_names"""
    variants_by_block = defaultdict(dict)
    for entry in blocks:
        if not entry["model_names"]:
            continue
        for stage in entry["stages"]:
            block_id, states = parse_block(stage["block"])
            key = state_key(states)
            models = [{"model": "derailed:block/" + path}
                      for path in stage_models(types, entry, stage)]
            variants_by_block[block_id].setdefault(key, []).extend(models)

    for block_id, variants in sorted(variants_by_block.items()):
        out[BLOCKSTATE_DIR / (block_id + ".json")] = {
            "variants": {k: variants[k] for k in sorted(variants)}
        }


def mineable_sets(families, blocks):
    """Maps (resource type, hardness family) to the block ids a tool rule for
    that pair must cover, alongside the blocks per resource type that no tool
    may mine until reachability unlocks them"""
    mineable = defaultdict(set)
    unmineable = defaultdict(set)
    for entry in blocks:
        resource = entry["resource_type"]
        for stage in entry["stages"]:
            block_id, _ = parse_block(stage["block"])
            if stage.get("mineable", True):
                mineable[(resource, family_of(families, block_id))].add(block_id)
            else:
                unmineable[resource].add(block_id)
    return mineable, unmineable


def build_tags(types, families, blocks, out):
    """Per category: one tag per tool rule, the blocks no tool may mine, and a
    roll-up of both"""
    mineable, unmineable = mineable_sets(families, blocks)
    members = defaultdict(list)

    for (resource, family), block_ids in sorted(mineable.items()):
        category = types[resource]["category"]
        name = "mineable_" + family
        out[TAG_DIR / category / (name + ".json")] = {"values": sorted(block_ids)}
        members[category].append("#derailed:%s/%s" % (category, name))

    for resource, block_ids in sorted(unmineable.items()):
        category = types[resource]["category"]
        out[TAG_DIR / category / "unmineable.json"] = {"values": sorted(block_ids)}
        members[category].append("#derailed:%s/unmineable" % category)

    for category, tags in sorted(members.items()):
        out[TAG_DIR / category / "all.json"] = {"values": sorted(tags)}


def build_functions(types, blocks, out):
    """Layer one dispatches on the resource block index, layer two on the stage
    that was mined"""
    lines = [
        GENERATED_HEADER,
        "# Dispatches a mined block to its chain. Run as the seed, at the seed",
        "",
    ]
    for index, entry in enumerate(blocks):
        lines.append("execute if score #mined_block dr_temp matches %d run "
                     "return run function derailed:generated/mined/block%d" % (index, index))
    out[FUNCTION_DIR / "dispatch.mcfunction"] = lines

    for index, entry in enumerate(blocks):
        stages = entry["stages"]
        resource = entry["resource_type"]
        body = [
            GENERATED_HEADER,
            "# Biome %s, %s. Run as the seed, at the seed" % (entry["biome"], resource),
            "",
        ]
        # Every stage but the last reveals the next block down the chain
        for stage_index in range(1, len(stages) - 1):
            body.append("execute if score #mined_stage dr_temp matches %d run "
                        "return run setblock ~ ~ ~ %s strict"
                        % (stage_index, stages[stage_index + 1]["block"]))

        body += [
            "",
            "# The last stage yields the resource itself. A drop appears within the",
            "#  block it came from, so aligning recovers the tile without guessing",
            "scoreboard players set #curr_item_count dr_arg 1",
            "scoreboard players operation #curr_item dr_arg = %s dr_const" % types[resource]["id"],
            "scoreboard players set #curr_rotation dr_arg 0",
            "execute align xyz positioned ~0.5 ~ ~0.5 run function derailed:item/place_new",
        ]
        out[FUNCTION_DIR / ("block%d.mcfunction" % index)] = body


def check_dangling_models(rendered, warn):
    """Warns about a blockstate pointing at a model file that is not there

    Moving or renaming a model leaves every blockstate that named it aiming at
    nothing, and the game reports that as a missing texture rather than as an
    error. Hand-written blockstates are checked too, since those are the ones
    no regeneration can fix"""
    for path in sorted(BLOCKSTATE_DIR.glob("*.json")):
        text = rendered.get(path)
        if text is None:
            text = path.read_text(encoding="utf-8")
        for ref in sorted(set(re.findall(r'"derailed:block/([\w/]+)"', text))):
            if not (MODEL_DIR / (ref + ".json")).is_file():
                warn("%s references missing model derailed:block/%s"
                     % (path.relative_to(ROOT).as_posix(), ref))


def prune_empty_dirs(directory):
    """Removes a directory an orphan left empty, and any parent it empties in
    turn. Stops at the generated roots so it can never walk out of the pack"""
    roots = {LOOT_TABLE_DIR, TAG_DIR, FUNCTION_DIR, BLOCKSTATE_DIR, MODEL_DIR}
    while directory not in roots and ROOT in directory.parents:
        if not directory.is_dir() or any(directory.iterdir()):
            return
        directory.rmdir()
        directory = directory.parent


def render(path, content):
    """JSON files get two-space indent, functions get their lines joined. Both
    are CRLF with a trailing newline, like every other file in the repo"""
    if isinstance(content, list):
        text = "\n".join(content)
    else:
        text = json.dumps(content, indent=2)
    return text.replace("\r\n", "\n").replace("\n", "\r\n") + "\r\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="report what would change without writing anything")
    parser.add_argument("--rules", action="store_true",
                        help="print the solved tool rules for fix_items.mcfunction")
    args = parser.parse_args()

    warnings = []
    families, types, blocks = load_source()
    resource_ids = load_resource_ids()
    try:
        validate(families, types, blocks, resource_ids, warnings.append)
    except SourceError as error:
        print("error: %s" % error, file=sys.stderr)
        return 1

    out = {}
    build_loot_tables(blocks, out)
    build_blockstates(types, blocks, out)
    build_tags(types, families, blocks, out)
    build_functions(types, blocks, out)

    rendered = {path: render(path, content) for path, content in out.items()}
    new_paths = sorted(p.relative_to(ROOT).as_posix() for p in rendered)
    old_paths = []
    if MANIFEST_FILE.is_file():
        old_paths = json.loads(MANIFEST_FILE.read_text(encoding="utf-8"))["paths"]
    orphans = [p for p in old_paths if p not in set(new_paths)]

    changed = []
    for path, text in sorted(rendered.items()):
        existing = path.read_bytes().decode("utf-8") if path.is_file() else None
        if existing != text:
            changed.append(path.relative_to(ROOT).as_posix())

    if args.check:
        for path in changed:
            print("would write  %s" % path)
        for path in orphans:
            print("would delete %s" % path)
    else:
        for path, text in sorted(rendered.items()):
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(text.encode("utf-8"))
        for path in orphans:
            target = ROOT / path
            if target.is_file():
                target.unlink()
            prune_empty_dirs(target.parent)
        MANIFEST_FILE.write_bytes(
            (json.dumps({"paths": new_paths}, indent=2).replace("\n", "\r\n") + "\r\n").encode("utf-8"))
        print("wrote %d files (%d changed), deleted %d orphans"
              % (len(rendered), len(changed), len(orphans)))

    # Files sitting in a generated directory that this run does not own are
    #  almost always leftovers from before the manifest existed
    check_dangling_models(rendered, warnings.append)

    for directory in (LOOT_TABLE_DIR, FUNCTION_DIR):
        if not directory.is_dir():
            continue
        for path in sorted(directory.iterdir()):
            if path.is_file() and path not in rendered:
                warnings.append("unmanaged file in a generated directory: %s"
                                % path.relative_to(ROOT).as_posix())

    # Only the pairs a chain actually uses, so an unused family never shows up
    #  as a rule the tool has to carry
    used = sorted(mineable_sets(families, blocks)[0])

    print()
    print("%-10s %-9s %-8s %-6s %s" % ("resource", "family", "hardness", "speed", "ticks"))
    for resource, family in used:
        hardness = families[family]["hardness"]
        speed = solved_speed(hardness, types[resource]["stage_ticks"])
        ticks = math.ceil(hardness * TICKS_PER_HARDNESS / speed)
        print("%-10s %-9s %-8s %-6s %d" % (resource, family, hardness, speed, ticks))

    if args.rules:
        print()
        for resource in sorted(types):
            rules = ",".join(
                "{blocks:'#derailed:%s/mineable_%s',speed:%s,correct_for_drops:true}"
                % (types[r]["category"], family,
                   solved_speed(families[family]["hardness"], types[r]["stage_ticks"]))
                for r, family in used if r == resource)
            print("%s: tool={default_mining_speed:0,rules:[%s]}" % (resource, rules))

    if warnings:
        print()
        for warning in warnings:
            print("warning: %s" % warning)
    return 0


if __name__ == "__main__":
    sys.exit(main())
